sudo: false
cache: bundler
language: ruby
env:
  matrix:
    - SOLIDUS_BRANCH=v1.3 DB=mysql
    - SOLIDUS_BRANCH=v1.3 DB=postgres
    - SOLIDUS_BRANCH=master DB=mysql
    - SOLIDUS_BRANCH=master DB=postgres
script:
  - bundle exec rake test_app
  - bundle exec rspec
rvm:
  - 2.1.8
